<a href="https://colab.research.google.com/github/stnrsita/python_for_datascience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
# pip install numpy

In [ ]:
import numpy as np

## Numpy Create Array

In [ ]:
#@title 0-D Array

var_array = np.array(42)

print(var_array)

42


In [ ]:
#@title 1-D Array

var_array = np.array([1, 2, 3, 4, 5])

print(var_array)

[1 2 3 4 5]


In [ ]:
var_array = np.ones(5)
print(var_array)

[1. 1. 1. 1. 1.]


In [ ]:
var_array = np.zeros(4)
print(var_array)

[0. 0. 0. 0.]


In [ ]:
var_array = np.random.random(6)
print(var_array)

[0.31012118 0.78170102 0.53481417 0.8988009  0.4768028  0.65877704]


In [ ]:
#@title 2-D Array

var_array = np.array([[1, 2, 3], [4, 5, 6]])
# var_array = np.array([[], []])

print(var_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
#@title 3-D Array

var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(var_array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#@title Check dimensi array

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#@title Create array range
#numpy.arange(start, stop, step)

var_array = np.arange(1, 20, 2)
print(var_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# create with reshape

var_array = np.arange(10).reshape((2, 5))
print(var_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# create numpy text

var_array = np.array(['apple', 'banana', 'cherry'])
print(var_array)

['apple' 'banana' 'cherry']


## Numpy Array Indexing

In [ ]:
#@title Akses indeks

# 1-D
var_array = np.array([85, 55, 40, 90])

# mengakses data pada array
print(var_array[3])

90


In [ ]:
# 2-D
var_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(var_array[1, 2])

8


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 2])

12


In [ ]:
#@title Operation indeks

var_array = np.array([1, 2, 3, 4])

print(var_array[2] + var_array[3])

7


In [ ]:
print(var_array[0] + var_array[2])

4


In [ ]:
#@title Slicing array

# 1-D
var_array = np.array([1, 2, 3, 4, 5, 6, 7])

print(var_array[3:])

[4 5 6 7]


In [ ]:
# 2-D
var_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(var_array[0, 1:4])

[2 3 4]


In [ ]:
# 3-D
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(var_array[1, 1, 0:2])

[10 11]


In [ ]:
#@title Iterating Arrays

var_array = np.array([1, 2, 3])

for x in var_array:
  print(x)

1
2
3


In [ ]:
var_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in var_array:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Numpy Array Join

In [ ]:
#@title Concatenate

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
var_array1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
var_array2 = np.array([[[4, 7, 9], [1, 6, 2]], [[3, 5, 8], [19, 10, 14]]])

arr = np.concatenate((var_array1, var_array2))
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 4  7  9]
  [ 1  6  2]]

 [[ 3  5  8]
  [19 10 14]]]


In [ ]:
#@title Stack

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# arr = np.stack((arr1, arr2))
# arr = np.hstack((arr1, arr2))
# arr = np.vstack((arr1, arr2))
# arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Numpy Splitting

In [ ]:
# 1-D
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# 2-D
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# 3-D
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
newarr = np.array_split(arr, 2)

print(newarr)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[ 7,  8,  9],
        [10, 11, 12]]])]


## Numpy Matriks

In [ ]:
matriks = [[1,2,3],
           [4,5,6],
           [7,8,9]]

matrik_np = np.array(matriks)
print(matrik_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#@title Operasi matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

matrik_b = np.array([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]])


hasil = matrik_a + matrik_b
print("Hasil Penjumlahan:")
print(hasil)

Hasil Penjumlahan:
[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


In [ ]:
hasil = matrik_a - matrik_b
print("Hasil Pengurangan:")
print(hasil)

Hasil Pengurangan:
[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


In [ ]:
# pangkat dengan power()

result_power = np.power(matrik_a, 2)
print("Hasil Perhitungan Pangkat (matrik_a pangkat 2):")
print(result_power)

Hasil Perhitungan Pangkat (matrik_a pangkat 2):
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
# trigonometri dengan sin()

result_power = np.sin(matrik_a)
print("Hasil sin matrik_a:")
print(result_power)

Hasil sin matrik_a:
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
#@title Transpose matrik

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)


hasil = matrik_a.transpose()
print("\nMatrik kebalikan: ")
print(hasil)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrik kebalikan: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#@title Reshape matrik

matrik_a = np.array([1, 2, 3, 4, 5, 6])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

# mengubah ukran ke 3x2
hasil = matrik_a.reshape(3, 2)

print("\nMengubah ke 3x2: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[1 2 3 4 5 6]
Ukuran =  (6,)

Mengubah ke 3x2: 
[[1 2]
 [3 4]
 [5 6]]
Ukuran =  (3, 2)


In [ ]:
#@title Matrik flatten

matrik_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print("Matrik awal: ")
print(matrik_a)
print("Ukuran = ", matrik_a.shape)

hasil = matrik_a.flatten()

print("\nMatrik setelah di-flatten: ")
print(hasil)
print("Ukuran = ", hasil.shape)

Matrik awal: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Ukuran =  (3, 3)

Matrik setelah di-flatten: 
[1 2 3 4 5 6 7 8 9]
Ukuran =  (9,)


## Numpy Statistik

In [ ]:
#@title rata-rata (mean)

data = np.array([12, 15, 18, 22, 30, 35, 40, 45, 55, 65])

mean = np.mean(data)
print("Rata-rata (mean):", mean)

Rata-rata (mean): 33.7


In [ ]:
#@title median

median = np.median(data)
print("Median:", median)

Median: 32.5


In [ ]:
#@title standard deviation

std_deviation = np.std(data)
print("Deviasi Standar (standard deviation):", std_deviation)

Deviasi Standar (standard deviation): 16.79315336677421


In [ ]:
#@title variansi (variance)

variance = np.var(data)
print("Variansi (variance):", variance)

Variansi (variance): 282.01


In [ ]:
#@title minimum dan maksimum

minimum = np.min(data)
maximum = np.max(data)
print("Nilai Minimum:", minimum)
print("Nilai Maksimum:", maximum)

Nilai Minimum: 12
Nilai Maksimum: 65


In [ ]:
#@title quartile

# Menghitung kuartil pertama (Q1) dan kuartil ketiga (Q3)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
print("Kuartil Pertama (Q1):", q1)
print("Kuartil Ketiga (Q3):", q3)


# Menghitung rentang interkuartil (IQR)
iqr = q3 - q1
print("Rentang Interkuartil (IQR):", iqr)

Kuartil Pertama (Q1): 19.0
Kuartil Ketiga (Q3): 43.75
Rentang Interkuartil (IQR): 24.75


## Soal 1

Buat contoh :

* numpy array (1D, 2D, 3D)
* numpy join
* numpy split
* operasi matrik

In [ ]:
import numpy as np

# Membuat array 1D
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]


In [ ]:
# Membuat array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(array_2d)


2D Array:
[[1 2 3]
 [4 5 6]]


In [ ]:
# Membuat array 3D
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(array_3d)


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Join 1D arrays
array_a_1d = np.array([1, 2, 3])
array_b_1d = np.array([4, 5, 6])

joined_1d = np.concatenate((array_a_1d, array_b_1d))
print("\nJoined 1D Array:")
print(joined_1d)


Joined 1D Array:
[1 2 3 4 5 6]


In [ ]:
# Join 2D arrays (di sepanjang axis=0)
array_a_2d = np.array([[1, 2], [3, 4]])
array_b_2d = np.array([[5, 6], [7, 8]])

joined_2d = np.concatenate((array_a_2d, array_b_2d), axis=0)
print("\nJoined 2D Array (axis=0):")
print(joined_2d)


Joined 2D Array (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# Join 3D arrays (di sepanjang axis=1)
array_a_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_b_3d = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

joined_3d = np.concatenate((array_a_3d, array_b_3d), axis=1)
print("\nJoined 3D Array (axis=1):")
print(joined_3d)


Joined 3D Array (axis=1):
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]


In [ ]:
# Split 1D array menjadi 3 bagian
array_1d_to_split = np.array([1, 2, 3, 4, 5, 6])

split_1d = np.split(array_1d_to_split, 3)
print("\nSplit 1D Array:")
for i, arr in enumerate(split_1d):
    print(f"Array {i + 1}: {arr}")


Split 1D Array:
Array 1: [1 2]
Array 2: [3 4]
Array 3: [5 6]


In [ ]:
# Split 2D array di sepanjang axis=1
array_2d_to_split = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

split_2d = np.split(array_2d_to_split, 2, axis=1)
print("\nSplit 2D Array (axis=1):")
for i, arr in enumerate(split_2d):
    print(f"Array {i + 1}:\n{arr}")


Split 2D Array (axis=1):
Array 1:
[[1 2]
 [5 6]]
Array 2:
[[3 4]
 [7 8]]


In [ ]:
# Split 3D array di sepanjang axis=2
array_3d_to_split = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

split_3d = np.split(array_3d_to_split, 3, axis=2)
print("\nSplit 3D Array (axis=2):")
for i, arr in enumerate(split_3d):
    print(f"Array {i + 1}:\n{arr}")


Split 3D Array (axis=2):
Array 1:
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]
Array 2:
[[[ 2]
  [ 5]]

 [[ 8]
  [11]]]
Array 3:
[[[ 3]
  [ 6]]

 [[ 9]
  [12]]]


In [ ]:
# Contoh operasi matriks
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Penjumlahan matriks
matrix_sum = matrix_a + matrix_b
print("\nMatrix Sum:")
print(matrix_sum)

# Perkalian matriks
matrix_product = np.dot(matrix_a, matrix_b)
print("\nMatrix Product:")
print(matrix_product)

# Transpose matriks
matrix_transpose = np.transpose(matrix_a)
print("\nMatrix Transpose:")
print(matrix_transpose)

# Determinan matriks
det_matrix = np.linalg.det(matrix_a)
print("\nDeterminant of Matrix A:")
print(det_matrix)


Matrix Sum:
[[ 6  8]
 [10 12]]

Matrix Product:
[[19 22]
 [43 50]]

Matrix Transpose:
[[1 3]
 [2 4]]

Determinant of Matrix A:
-2.0000000000000004


## Soal 2

* Buatlah numpy array dengan matrik ukuran 3x4 dan range array 10-30
* Kemudian lakukan flatten
* cari nilai statistik (mean, median, dsb)

In [ ]:
# Membuat matriks 3x4 dengan rentang 10-30
matrix = np.random.randint(10, 31, size=(3, 4))
print("Matriks 3x4:")
print(matrix)

# Melakukan flatten pada matriks
flattened_array = matrix.flatten()
print("\nFlattened Array:")
print(flattened_array)

# Menghitung nilai statistik
mean_value = np.mean(flattened_array)
median_value = np.median(flattened_array)
std_dev_value = np.std(flattened_array)
max_value = np.max(flattened_array)
min_value = np.min(flattened_array)
variance_value = np.var(flattened_array)
quartile1 = np.percentile(flattened_array, 25)
quartile3 = np.percentile(flattened_array, 75)

# Menampilkan hasil
print("\nStatistik:")
print(f"Mean: {mean_value}")
print(f"Median: {median_value}")
print(f"Standar Deviasi: {std_dev_value}")
print(f"Maksimum: {max_value}")
print(f"Minimum: {min_value}")
print(f"Variansi: {variance_value}")
print(f"Kuartil 1: {quartile1}")
print(f"Kuartil 3: {quartile3}")

Matriks 3x4:
[[25 27 20 19]
 [27 10 10 23]
 [29 23 28 17]]

Flattened Array:
[25 27 20 19 27 10 10 23 29 23 28 17]

Statistik:
Mean: 21.5
Median: 23.0
Standar Deviasi: 6.251666444503684
Maksimum: 29
Minimum: 10
Variansi: 39.083333333333336
Kuartil 1: 18.5
Kuartil 3: 27.0
